name: Fetch Blog Posts and Deploy

on:
  # Run twice daily at 8 AM and 8 PM UTC
  schedule:
    - cron: '0 8,20 * * *'

  # Allow manual trigger
  workflow_dispatch:

  # Run on push to main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  fetch-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch blog posts from RSS feeds
        run: |
          python3 scripts/fetch_blog_posts.py

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: sramkrishna/sramkrishna.github.io
          publish_branch: main
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
